<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'

type Product = { id: string | number; name: string; category: string; price: number; stock: number; icon: string; tone: string; minimumStock?: number }
type CartLine = Product & { quantity: number }
type Receipt = { invoiceNo: string; createdAt: string; total: number; payment: string; lines: CartLine[] }

const activeView = ref('Overview')
const search = ref('')
const selectedCategory = ref('All items')
const payment = ref('Card')
const discount = ref(0)
const completed = ref(false)
const products = ref<Product[]>([
  { id: 1, name: 'Nexa Cold Brew', category: 'Drinks', price: 4.5, stock: 34, icon: '☕', tone: 'coffee' },
  { id: 2, name: 'Matcha Oat Latte', category: 'Drinks', price: 5.25, stock: 18, icon: '🍵', tone: 'matcha' },
  { id: 3, name: 'Sparkling Water', category: 'Drinks', price: 2, stock: 48, icon: '◌', tone: 'water' },
  { id: 4, name: 'Sea Salt Chips', category: 'Snacks', price: 2.75, stock: 12, icon: '◒', tone: 'chips' },
  { id: 5, name: 'Almond Croissant', category: 'Bakery', price: 3.95, stock: 7, icon: '🥐', tone: 'croissant' },
  { id: 6, name: 'Berry Yogurt Bowl', category: 'Food', price: 6.5, stock: 9, icon: '◉', tone: 'berry' },
  { id: 7, name: 'Avocado Toast', category: 'Food', price: 7.75, stock: 15, icon: '◈', tone: 'avocado' },
  { id: 8, name: 'Chocolate Cookie', category: 'Bakery', price: 2.25, stock: 22, icon: '●', tone: 'cookie' },
])
const cart = ref<CartLine[]>([{ ...products.value[0], quantity: 1 }, { ...products.value[3], quantity: 2 }])
const categories = computed(() => ['All items', ...new Set(products.value.map((item) => item.category))])
const nav = [['Overview','⌘'], ['Sell','▣'], ['Orders','◫'], ['Products','◇'], ['Inventory','▤'], ['Customers','♙'], ['Analytics','◔'], ['Team','♧']]
const filteredProducts = computed(() => products.value.filter((item) => (selectedCategory.value === 'All items' || item.category === selectedCategory.value) && item.name.toLowerCase().includes(search.value.toLowerCase())))
const subtotal = computed(() => cart.value.reduce((sum, item) => sum + item.price * item.quantity, 0))
const tax = computed(() => subtotal.value * 0.08)
const total = computed(() => Math.max(0, subtotal.value + tax.value - discount.value))
const apiUrl = import.meta.env.VITE_API_URL ?? 'http://localhost:3000/api'
const apiStatus = ref<'demo' | 'connected'>('demo')
const showProductForm = ref(false)
const processing = ref(false)
const receipt = ref<Receipt | null>(null)
const productForm = ref({ name: '', category: 'General', price: 0, stock: 0 })
const money = (value: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value)
function addToCart(product: Product) { const line = cart.value.find((item) => item.id === product.id); if (line) line.quantity++; else cart.value.push({ ...product, quantity: 1 }); completed.value = false }
function changeQuantity(id: string | number, amount: number) { const line = cart.value.find((item) => item.id === id); if (!line || (amount > 0 && line.quantity >= line.stock)) return; line.quantity += amount; if (line.quantity < 1) cart.value = cart.value.filter((item) => item.id !== id) }
async function addProduct() { if (!productForm.value.name || productForm.value.price <= 0) return; const draft = { ...productForm.value }; try { if (apiStatus.value === 'connected') { const response = await fetch(`${apiUrl}/products`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: draft.name, category: draft.category || 'General', retailPrice: draft.price, openingStock: draft.stock }) }); if (!response.ok) throw new Error('Could not add product'); await loadProducts() } else products.value.unshift({ id: `local-${Date.now()}`, name: draft.name, category: draft.category || 'General', price: Number(draft.price), stock: Number(draft.stock), minimumStock: 10, icon: '✦', tone: 'water' }); productForm.value = { name: '', category: 'General', price: 0, stock: 0 }; showProductForm.value = false } catch { alert('Product save nahi hua. API/database connection check karein.') } }
async function loadProducts() { try { const response = await fetch(`${apiUrl}/products`); if (!response.ok) return; const rows = await response.json(); products.value = rows.map((item: any, index: number) => ({ id: item.id, name: item.name, category: item.category?.name ?? 'General', price: Number(item.retailPrice), stock: item.stock?.quantity ?? 0, minimumStock: item.minimumStock, icon: ['☕','🍵','◌','◒','🥐'][index % 5], tone: ['coffee','matcha','water','chips','croissant'][index % 5] })); apiStatus.value = 'connected' } catch { apiStatus.value = 'demo' } }
async function checkout() { if (!cart.value.length || processing.value) return; processing.value = true; const lines = cart.value.map((item) => ({ ...item })); try { if (apiStatus.value === 'connected' && lines.every((item) => typeof item.id === 'string')) { const response = await fetch(`${apiUrl}/sales`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ paymentMode: payment.value.toUpperCase(), discount: discount.value, items: lines.map((item) => ({ productId: item.id, quantity: item.quantity, unitPrice: item.price })) }) }); if (!response.ok) throw new Error('Sale could not be saved'); const sale = await response.json(); receipt.value = { invoiceNo: sale.invoiceNo, createdAt: new Date().toLocaleString(), total: Number(sale.totalAmount), payment: payment.value, lines } } else receipt.value = { invoiceNo: `NT-${Date.now().toString().slice(-6)}`, createdAt: new Date().toLocaleString(), total: total.value, payment: payment.value, lines }; completed.value = true; lines.forEach((line) => { const p = products.value.find((item) => item.id === line.id); if (p) p.stock -= line.quantity }); cart.value = []; discount.value = 0 } catch { alert('Sale save nahi hui. API/database connection check karein.') } finally { processing.value = false } }
function printReceipt() { window.print() }
onMounted(loadProducts)
</script>

<template>
  <main class="app-shell">
    <aside class="sidebar">
      <div class="brand"><span class="brand-mark">N</span><span>Nexa<span>Till</span></span></div>
      <div class="store"><i>✦</i><div><b>Northstar Market</b><small>Downtown · Register 01</small></div><span>⌄</span></div>
      <nav><button v-for="item in nav" :key="item[0]" :class="{active: activeView === item[0]}" @click="activeView = item[0]"><i>{{ item[1] }}</i><span>{{ item[0] }}</span><em v-if="item[0] === 'Orders'">4</em></button></nav>
      <div class="side-bottom"><button><i>?</i><span>Help center</span></button><div class="user"><strong>SK</strong><div><b>Sofia Kaif</b><small>Store manager</small></div><span>⋮</span></div></div>
    </aside>
    <section class="workspace">
      <header><div><p>Tuesday, March 12</p><h1>{{ activeView === 'Overview' ? 'Good morning, Sofia' : activeView }}</h1></div><div class="header-actions"><button class="utility">⌕</button><button class="utility dot">♧</button><button class="new-sale" @click="activeView = 'Sell'">+ New sale <kbd>⌘ K</kbd></button></div></header>
      <template v-if="activeView === 'Overview'">
        <section class="stats">
          <article><i class="mint">↗</i><div><span>Today's sales</span><b>$2,846.50</b><small class="up">↑ 12.5% <em>vs. yesterday</em></small></div><svg class="spark green" viewBox="0 0 100 40"><path d="M0 33C14 21 18 31 29 19S44 28 52 13S67 20 76 8S88 8 100 1"/></svg></article>
          <article><i class="purple">▣</i><div><span>Orders</span><b>128</b><small class="up">↑ 8.2% <em>vs. yesterday</em></small></div><svg class="spark violet" viewBox="0 0 100 40"><path d="M0 30C15 26 17 34 29 18S42 27 53 19S68 28 76 9S92 21 100 3"/></svg></article>
          <article><i class="amber">◎</i><div><span>Average order</span><b>$22.24</b><small class="down">↓ 2.4% <em>vs. yesterday</em></small></div><svg class="spark orange" viewBox="0 0 100 40"><path d="M0 10C15 17 17 4 29 17S43 11 52 23S66 12 75 25S91 18 100 32"/></svg></article>
          <article><i class="blue">◒</i><div><span>Low stock items</span><b>9</b><small class="warn">Needs attention</small></div><button class="arrow" @click="activeView='Inventory'">→</button></article>
        </section>
        <section class="dashboard">
          <article class="panel sales"><div class="panel-head"><div><h2>Sales overview</h2><p>Revenue performance this week</p></div><button>This week ⌄</button></div><div class="chart"><div class="y-labels"><span>$1.2k</span><span>$900</span><span>$600</span><span>$300</span><span>$0</span></div><div class="bars"><div v-for="(height,index) in [52,68,44,86,61,92,70]" :key="index"><i :style="{height: height + '%'}"></i><span>{{ ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][index] }}</span></div></div><aside><b>$6,482.90</b><span>Total sales</span><small>↑ 14.8%</small></aside></div></article>
          <article class="panel channels"><div class="panel-head"><div><h2>Sales channels</h2><p>Today’s transaction mix</p></div><button class="more">•••</button></div><div class="channel-body"><div class="donut"><div><b>128</b><span>orders</span></div></div><div class="legend"><p><i class="direct"></i>In-store <b>76%</b><small>97 orders</small></p><p><i class="pickup"></i>Pickup <b>16%</b><small>20 orders</small></p><p><i class="online"></i>Online <b>8%</b><small>11 orders</small></p></div></div></article>
          <article class="panel top-products"><div class="panel-head"><div><h2>Top products</h2><p>By units sold today</p></div><button class="link" @click="activeView='Products'">View all →</button></div><div v-for="(product,index) in products.slice(0,4)" :key="product.id" class="top-row"><span>0{{index+1}}</span><i :class="product.tone">{{ product.icon }}</i><div><b>{{product.name}}</b><small>{{[42,36,29,24][index]}} sold</small></div><strong>{{money(product.price * [42,36,29,24][index])}}</strong><em><i :style="{width:[92,78,63,51][index]+'%'}"></i></em></div></article>
          <article class="panel activity"><div class="panel-head"><div><h2>Recent activity</h2><p>Live store updates</p></div><button class="more">•••</button></div><div class="activity-row"><i class="done">✓</i><div><b>Order #NT-10428 completed</b><small>Card payment · $24.50</small></div><time>2 min</time></div><div class="activity-row"><i class="low">!</i><div><b>Low stock: Almond Croissant</b><small>7 units remaining</small></div><time>18 min</time></div><div class="activity-row"><i class="added">+</i><div><b>New customer added</b><small>Amelia Roberts</small></div><time>34 min</time></div><button class="view-all">View all activity</button></article>
        </section>
      </template>
      <template v-else-if="activeView === 'Sell'">
        <section class="pos">
          <article class="panel catalog"><div class="catalog-tools"><label><span>⌕</span><input v-model="search" placeholder="Search products or scan barcode"><kbd>⌘ F</kbd></label><button @click="showProductForm=true">+ Product</button></div><div class="pos-meta"><span :class="apiStatus">{{apiStatus === 'connected' ? '● Live API catalog' : '● Demo catalog — API offline'}}</span><button @click="loadProducts">↻ Refresh</button></div><div class="categories"><button v-for="category in categories" :key="category" :class="{selected: category===selectedCategory}" @click="selectedCategory=category">{{category}}</button></div><div class="product-grid"><button v-for="product in filteredProducts" :key="product.id" :disabled="product.stock < 1" @click="addToCart(product)"><i :class="product.tone">{{product.icon}}</i><b>{{product.name}}</b><span>{{money(product.price)}}</span><small :class="{lowText: product.stock <= (product.minimumStock ?? 10)}">{{product.stock < 1 ? 'Out of stock' : product.stock + ' in stock'}}</small><em>+</em></button></div></article>
          <aside class="panel checkout"><div class="checkout-head"><div><p>CURRENT ORDER</p><h2>New sale <span>#NT-10429</span></h2></div><button class="more">•••</button></div><div class="customer"><i>♙</i><div><b>Walk-in customer</b><small>Add customer for rewards</small></div><button>+</button></div><div class="cart"><p v-if="!cart.length" class="empty">Your cart is waiting.<br>Select products to begin.</p><div v-for="line in cart" :key="line.id" class="cart-line"><i :class="line.tone">{{line.icon}}</i><div><b>{{line.name}}</b><small>{{money(line.price)}} each</small></div><label><button @click="changeQuantity(line.id,-1)">−</button><span>{{line.quantity}}</span><button @click="changeQuantity(line.id,1)">+</button></label><strong>{{money(line.price*line.quantity)}}</strong></div></div><div class="summary"><p><span>Subtotal</span><b>{{money(subtotal)}}</b></p><p><span>Tax <small>(8%)</small></span><b>{{money(tax)}}</b></p><button @click="discount=discount?0:2"><span>⌁ {{discount?'Remove discount':'Add discount'}}</span><b>{{discount?'−'+money(discount):'+'}}</b></button><div><span>Total</span><b>{{money(total)}}</b></div></div><div class="payments"><button v-for="method in ['Cash','Card','Split']" :key="method" :class="{selected:payment===method}" @click="payment=method"><i>{{method==='Cash'?'$':method==='Card'?'▣':'÷'}}</i>{{method}}</button></div><button class="charge" :disabled="!cart.length || processing" @click="checkout">{{processing?'Saving sale…':`Charge ${money(total)}`}} <span>→</span></button></aside>
        </section>
      </template>
      <section v-else class="panel placeholder"><i>{{activeView==='Inventory'?'▤':activeView==='Products'?'◇':'◫'}}</i><p>NEXATILL MANAGEMENT</p><h2>{{activeView}} workspace</h2><span>This advanced module is ready to connect with your NestJS API. Use the Sell workspace for the complete live POS flow.</span><button class="new-sale" @click="activeView=activeView==='Inventory'?'Sell':'Overview'">{{activeView==='Inventory'?'Review low stock':'Back to overview'}} →</button></section>
      <div v-if="showProductForm" class="modal-backdrop"><form class="modal" @submit.prevent="addProduct"><button type="button" class="close" @click="showProductForm=false">×</button><p>CATALOG MANAGEMENT</p><h2>Add new product</h2><label>Product name<input v-model.trim="productForm.name" required placeholder="e.g. Mineral Water 500ml"></label><label>Category<input v-model.trim="productForm.category" placeholder="Drinks"></label><div class="form-row"><label>Retail price<input v-model.number="productForm.price" type="number" min="0.01" step="0.01" required></label><label>Opening stock<input v-model.number="productForm.stock" type="number" min="0" required></label></div><button class="new-sale" type="submit">Add to catalog →</button></form></div>
      <div v-if="receipt" class="modal-backdrop"><article class="receipt"><button class="close" @click="receipt=null">×</button><div class="receipt-brand"><b>Nexa<span>Till</span></b><small>Northstar Market · Downtown</small></div><h2>Payment successful</h2><p>{{receipt.invoiceNo}} · {{receipt.createdAt}}</p><div v-for="line in receipt.lines" :key="line.id" class="receipt-line"><span>{{line.quantity}} × {{line.name}}</span><b>{{money(line.quantity * line.price)}}</b></div><div class="receipt-total"><span>Total paid via {{receipt.payment}}</span><b>{{money(receipt.total)}}</b></div><button class="new-sale" @click="printReceipt">Print receipt</button><button class="plain" @click="receipt=null">Start next sale</button></article></div>
    </section>
  </main>
</template>

<style scoped>
.pos-meta{display:flex;justify-content:space-between;padding:12px 0 0;color:#8a93a0;font-size:10px}.pos-meta button{background:none;color:#267a57;font-size:10px;font-weight:700}.pos-meta .connected{color:#1b9b6e}.lowText{color:#d08027!important;font-weight:700}.product-grid button:disabled{opacity:.48;cursor:not-allowed;filter:grayscale(.3)}.modal-backdrop{position:fixed;z-index:20;inset:0;display:grid;place-items:center;padding:20px;background:#18203488;backdrop-filter:blur(4px)}.modal,.receipt{position:relative;width:min(100%,400px);padding:27px;border-radius:16px;background:#fff;box-shadow:0 24px 70px #11182755}.modal p,.receipt-brand small{display:block;margin:0 0 6px;color:#8993a0;font-size:10px;font-weight:700;letter-spacing:.7px}.modal h2,.receipt h2{margin:0 0 20px;font:700 21px Manrope}.close{position:absolute;top:13px;right:13px;width:27px;height:27px;border-radius:50%;background:#f0f2f3;color:#65707a;font-size:19px}.modal label{display:block;margin:12px 0;color:#59616c;font-size:11px;font-weight:700}.modal input{display:block;width:100%;margin-top:6px;padding:10px;border:1px solid #dde2e5;border-radius:8px;outline-color:#75cfaa;font-size:12px}.form-row{display:grid;grid-template-columns:1fr 1fr;gap:10px}.modal .new-sale{width:100%;margin-top:13px}.receipt{text-align:center}.receipt-brand b{display:block;font:700 22px Manrope;color:#202432}.receipt-brand b span{color:#44b983}.receipt h2{margin-top:22px;margin-bottom:5px;font-size:18px}.receipt>p{margin:0 0 20px;color:#9299a6;font-size:10px}.receipt-line{display:flex;justify-content:space-between;padding:9px 0;border-bottom:1px dashed #dfe4e5;color:#58606b;font-size:11px;text-align:left}.receipt-line b,.receipt-total b{color:#252a35}.receipt-total{display:flex;justify-content:space-between;margin:15px 0 18px;color:#65707a;font-size:11px}.receipt-total b{font:700 17px Manrope}.receipt .new-sale{width:100%;margin-bottom:8px}.plain{width:100%;padding:9px;background:none;color:#597f70;font-size:11px;font-weight:700}@media print{.app-shell,.modal-backdrop:has(.receipt)~*{display:none}.modal-backdrop{position:static;padding:0;background:white}.receipt{box-shadow:none}}
</style>
